# Default front-matter variables: global, pages and posts
defaults:
- scope:
    path: ""
  values:
    lang: "en"

- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

- scope:
    path: ""
    type: "posts"
  values:
    layout:     "post"
    date_fmt:   "%F"
    categories: "news"
    comments:   false

exclude:
- assets/css/style.css
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- Gemfile
- Gemfile.lock
- LICENSE
- new_post.sh
- node_modules
- package.json
- package-lock.json
- Rakefile
- README.md
- setup.sh
- TODO.md
- yarn.lock
- yarn-error.log

plugins:
- jekyll-sitemap

name: "SFZ Instruments"
url: "https://sfzinstruments.github.io"
description: "SFZ Instruments Website"

repository:
  branch: "master"
  url: "https://github.com/sfzinstruments/sfzinstruments.github.io"

locale:
  default: "en"

authors:
  content: "Karoryfer Samples and SFZ Format Team"
  web: "RedTide and SFZ Format Team"
